#!/bin/sh

dotfiles_dir="$(cd "$( dirname "$0" )" && pwd)"

link() {
  case $1 in
    ~/*)
      source_filepath=$1;;
    *)
      source_filepath="$dotfiles_dir/$1";;
  esac

  ln -s "$source_filepath" "$2"
  echo "$source_filepath -> $2: $(test $? && echo 'Failed' || echo 'Succeed')"
  echo ''
}

mkdir -p \
  ~/.config/nvim/backup \
  ~/.config/nvim/swap \
  ~/.config/nvim/undo

link .vimrc ~/.vimrc
link .vimrc ~/.config/nvim/init.vim
link ~/.config/nvim ~/.vim

link .gitconfig ~/.gitconfig
link .zshrc ~/.zshrc
link alacritty.yml ~/.config/alacritty.yml
link starship.toml ~/.config/starship.toml

# Only for Linux.
if [ "$(uname)" = 'Linux' ]; then
  link .fehbg ~/.fehbg
  link .fbtermrc ~/.fbtermrc
  link .Xresources ~/.Xresources
  link .Xresources.flan ~/.Xresources.flan
  link .Xresources.rosetta ~/.Xresources.rosetta
  link .xinitrc ~/.xinitrc
  link .Xmodmap ~/.Xmodmap
  link i3status.conf ~/.config/i3status/config
  link i3config ~/.config/i3/config
  link i3exit ~/.config/i3/i3exit
fi
