#!/bin/sh

dotfiles_dir="$(cd "$( dirname "$0" )" && pwd)"

link() {
  case $1 in
    ~/*)
      source_filepath=$1;;
    *)
      source_filepath="$dotfiles_dir/$1";;
  esac

  ln -s "$source_filepath" "$2"
  echo -n "$source_filepath -> $2: "
  case $? in
      0 ) echo 'Succeed' ;;
      * ) echo "Failed ($?)" ;;
  esac
}

mkdir -p \
  ~/.config/nvim/backup \
  ~/.config/nvim/sessions \
  ~/.config/nvim/swap \
  ~/.config/nvim/undo

link .vimrc ~/.vimrc
link .vimrc ~/.config/nvim/init.vim
link ~/.config/nvim ~/.vim

link .gitconfig ~/.config/git/config
link .zshrc ~/.zshrc
link alacritty.toml ~/.config/alacritty.toml
link starship.toml ~/.config/starship.toml

# Only for Linux.
if [ "$(uname)" = 'Linux' ]; then
  link .fehbg ~/.fehbg
  link .Xresources ~/.Xresources
  link .Xresources.flan ~/.Xresources.flan
  link .Xresources.rosetta ~/.Xresources.rosetta
  link .xinitrc ~/.xinitrc
  link .Xmodmap ~/.Xmodmap
  mkdir -p ~/.config/i3 ~/.config/i3status
  link i3status.conf ~/.config/i3status/config
  link i3config ~/.config/i3/config
  link i3exit ~/.config/i3/i3exit
  link gtk-3.0/settings.ini ~/.config/gtk-3.0/settings.ini
fi
