command_timeout=1000

[hostname]
ssh_only = false
style = "bold fg:125"

[kubernetes]
disabled = false
format = '[$symbol$namespace]($style) in '

[docker_context]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[character]
success_symbol = "[>](bold green)"
